spring:
        datasource:
                url: mysql@test:172.18.3.28:1521/temp
                username: yj
                password: "{cipher}AQCtRW5VMwKgzlMLR/D2JtpndHUOOJXAbbuIelmpj2rORVAtrARQPjBSG38L/jm9kTzUwsXmQIkhdrEvtJD89vKdJja+0gJmiax8ihKVfU2Yi/kbtn7huZDJlp6W8lJYyzAdiD1PeEGdmKfhsmXjBecrv2oWM/JkwhOqSUrUKuzZDSlsofvqi+KbL/5WII5/LJEwJSlctKDZgETRF/HCu6fZ6FYVIn03bhbx6uTqQer+DuEDGg33dlmCZetoJ/An8Bf+XnT26ChRYTMAb80ILbSo7XcU7om5V4Tfk7LnEIRKranf9AU76rhz5fRxsxvFbdr8gNB2cIlbS8oR1MsEqm5RZmnJDj17efdtYShRlpuc+uU9/7ttigMD1oAIeKdHW/4="
